In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [4]:
df=pd.read_csv("dataset.csv")
df.shape
df.head()

C:\Users\diksh\AppData\Local\Temp\ipykernel_47688\1280691953.py:1: DtypeWarning: Columns (89) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("dataset.csv")

,CASE_NUMBER,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,ORIGINAL_CERT_DATE,VISA_CLASS,JOB_TITLE,SOC_CODE,SOC_TITLE,FULL_TIME_POSITION,...,WILLFUL_VIOLATOR,SUPPORT_H1B,STATUTORY_BASIS,APPENDIX_A_ATTACHED,PUBLIC_DISCLOSURE,PREPARER_LAST_NAME,PREPARER_FIRST_NAME,PREPARER_MIDDLE_INITIAL,PREPARER_BUSINESS_NAME,PREPARER_EMAIL
0,I-200-21270-606997,Certified,2021-09-26,2021-10-01,NaN,H-1B,APPLICATIONS SUPPORT ANALYST/ADMINISTRATOR,15-1132.00,"Software Developers, Applications",Y,...,No,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN
1,I-200-21270-606867,Certified,2021-09-26,2021-10-01,NaN,H-1B,Designer,17-3013.00,Mechanical Drafters,Y,...,No,NaN,NaN,NaN,Disclose Business and Employment,Stacey,Francyne,NaN,Stacey Law Practice,francyne@staceylawpractice.com
2,I-200-21270-606846,Certified,2021-09-26,2021-10-01,NaN,H-1B,Data Analyst,15-2031.00,Operations Research Analysts,Y,...,No,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN
3,I-200-21270-606842,Certified,2021-09-26,2021-10-01,NaN,H-1B,Pharmaceutical Chemist,19-2031.00,Chemists,Y,...,No,NaN,NaN,NaN,Disclose Business,JONNALAGADDA,SRINIVASA,R,"S. R. JONNALAGADDA, P.C.",Lawassociates@att.net
4,I-200-21270-606941,Certified,2021-09-26,2021-10-01,NaN,H-1B,Senior Systems Analyst JC60,15-1121.00,Computer Systems Analysts,Y,...,No,Yes,"$60,000 or higher annual wage",NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN

In [5]:
print("Shape:", df.shape)
df.head()

Shape: (201025, 96)

,CASE_NUMBER,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,ORIGINAL_CERT_DATE,VISA_CLASS,JOB_TITLE,SOC_CODE,SOC_TITLE,FULL_TIME_POSITION,...,WILLFUL_VIOLATOR,SUPPORT_H1B,STATUTORY_BASIS,APPENDIX_A_ATTACHED,PUBLIC_DISCLOSURE,PREPARER_LAST_NAME,PREPARER_FIRST_NAME,PREPARER_MIDDLE_INITIAL,PREPARER_BUSINESS_NAME,PREPARER_EMAIL
0,I-200-21270-606997,Certified,2021-09-26,2021-10-01,NaN,H-1B,APPLICATIONS SUPPORT ANALYST/ADMINISTRATOR,15-1132.00,"Software Developers, Applications",Y,...,No,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN
1,I-200-21270-606867,Certified,2021-09-26,2021-10-01,NaN,H-1B,Designer,17-3013.00,Mechanical Drafters,Y,...,No,NaN,NaN,NaN,Disclose Business and Employment,Stacey,Francyne,NaN,Stacey Law Practice,francyne@staceylawpractice.com
2,I-200-21270-606846,Certified,2021-09-26,2021-10-01,NaN,H-1B,Data Analyst,15-2031.00,Operations Research Analysts,Y,...,No,NaN,NaN,NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN
3,I-200-21270-606842,Certified,2021-09-26,2021-10-01,NaN,H-1B,Pharmaceutical Chemist,19-2031.00,Chemists,Y,...,No,NaN,NaN,NaN,Disclose Business,JONNALAGADDA,SRINIVASA,R,"S. R. JONNALAGADDA, P.C.",Lawassociates@att.net
4,I-200-21270-606941,Certified,2021-09-26,2021-10-01,NaN,H-1B,Senior Systems Analyst JC60,15-1121.00,Computer Systems Analysts,Y,...,No,Yes,"$60,000 or higher annual wage",NaN,Disclose Business,NaN,NaN,NaN,NaN,NaN

In [6]:
print(df.isnull().sum())

CASE_NUMBER                     0
CASE_STATUS                     0
RECEIVED_DATE                   0
DECISION_DATE                   0
ORIGINAL_CERT_DATE         188423
                            ...
PREPARER_LAST_NAME          95392
PREPARER_FIRST_NAME         95396
PREPARER_MIDDLE_INITIAL    164055
PREPARER_BUSINESS_NAME      92582
PREPARER_EMAIL              93686
Length: 96, dtype: int64

In [7]:
# num_cols = df.select_dtypes(include=np.number).columns
# cat_cols = df.select_dtypes(include='object').columns

# df[num_cols] = df[num_cols].fillna(df[num_cols].median())
# df[cat_cols] = df[cat_cols].apply(lambda x: x.fillna(x.mode()[0]))

# print("\nMissing Values After:\n")
# print(df.isnull().sum())

In [8]:
# print(df.columns)

In [9]:
columns = [
'CASE_STATUS',
'RECEIVED_DATE',
'DECISION_DATE',
'VISA_CLASS',
'JOB_TITLE',
'FULL_TIME_POSITION',
'EMPLOYER_STATE',
'WORKSITE_STATE',
'WAGE_RATE_OF_PAY_FROM',
'PREVAILING_WAGE'
]

df = df[columns]
df.head()

,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,VISA_CLASS,JOB_TITLE,FULL_TIME_POSITION,EMPLOYER_STATE,WORKSITE_STATE,WAGE_RATE_OF_PAY_FROM,PREVAILING_WAGE
0,Certified,2021-09-26,2021-10-01,H-1B,APPLICATIONS SUPPORT ANALYST/ADMINISTRATOR,Y,NJ,GA,92000.0,87485.0
1,Certified,2021-09-26,2021-10-01,H-1B,Designer,Y,MI,MI,56181.0,56181.0
2,Certified,2021-09-26,2021-10-01,H-1B,Data Analyst,Y,FL,MA,60000.0,59238.0
3,Certified,2021-09-26,2021-10-01,H-1B,Pharmaceutical Chemist,Y,MN,MN,56160.0,53851.0
4,Certified,2021-09-26,2021-10-01,H-1B,Senior Systems Analyst JC60,Y,TX,TN,70325.0,70325.0

In [10]:
df = df.dropna()

print("After removing missing values:")
print(df.shape)

After removing missing values:
(200998, 10)

In [11]:
df['RECEIVED_DATE'] = pd.to_datetime(df['RECEIVED_DATE'], errors='coerce')
df['DECISION_DATE'] = pd.to_datetime(df['DECISION_DATE'], errors='coerce')

In [12]:
print(df[['RECEIVED_DATE', 'DECISION_DATE']].dtypes)

RECEIVED_DATE    datetime64[ns]
DECISION_DATE    datetime64[ns]
dtype: object

In [13]:
df['processing_days'] = (df['DECISION_DATE'] - df['RECEIVED_DATE']).dt.days
df = df[df['processing_days'] >= 0]
df.head()

,CASE_STATUS,RECEIVED_DATE,DECISION_DATE,VISA_CLASS,JOB_TITLE,FULL_TIME_POSITION,EMPLOYER_STATE,WORKSITE_STATE,WAGE_RATE_OF_PAY_FROM,PREVAILING_WAGE,processing_days
0,Certified,2021-09-26,2021-10-01,H-1B,APPLICATIONS SUPPORT ANALYST/ADMINISTRATOR,Y,NJ,GA,92000.0,87485.0,5
1,Certified,2021-09-26,2021-10-01,H-1B,Designer,Y,MI,MI,56181.0,56181.0,5
2,Certified,2021-09-26,2021-10-01,H-1B,Data Analyst,Y,FL,MA,60000.0,59238.0,5
3,Certified,2021-09-26,2021-10-01,H-1B,Pharmaceutical Chemist,Y,MN,MN,56160.0,53851.0,5
4,Certified,2021-09-26,2021-10-01,H-1B,Senior Systems Analyst JC60,Y,TX,TN,70325.0,70325.0,5

In [14]:
df[['RECEIVED_DATE', 'DECISION_DATE', 'processing_days']]

       RECEIVED_DATE DECISION_DATE  processing_days
0         2021-09-26    2021-10-01                5
1         2021-09-26    2021-10-01                5
2         2021-09-26    2021-10-01                5
3         2021-09-26    2021-10-01                5
4         2021-09-26    2021-10-01                5
...              ...           ...              ...
201020    2022-03-02    2022-03-09                7
201021    2022-03-02    2022-03-09                7
201022    2022-03-02    2022-03-09                7
201023    2022-03-02    2022-03-09                7
201024    2022-03-02    2022-03-09                7

[200998 rows x 3 columns]

In [15]:
encoder = LabelEncoder()

categorical_cols = [
'CASE_STATUS',
'VISA_CLASS',
'JOB_TITLE',
'FULL_TIME_POSITION',
'EMPLOYER_STATE',
'WORKSITE_STATE'
]

for col in categorical_cols:
    df[col] = encoder.fit_transform(df[col])

In [16]:
scaler = StandardScaler()

df[['WAGE_RATE_OF_PAY_FROM','PREVAILING_WAGE']] = scaler.fit_transform(
    df[['WAGE_RATE_OF_PAY_FROM','PREVAILING_WAGE']]
)

In [17]:
df = df.drop(columns=['RECEIVED_DATE','DECISION_DATE'])
df.head()

,CASE_STATUS,VISA_CLASS,JOB_TITLE,FULL_TIME_POSITION,EMPLOYER_STATE,WORKSITE_STATE,WAGE_RATE_OF_PAY_FROM,PREVAILING_WAGE,processing_days
0,0,1,1009,1,34,10,-0.278511,-0.251113,5
1,0,1,12013,1,24,23,-0.734014,-1.037296,5
2,0,1,10836,1,9,20,-0.685448,-0.960521,5
3,0,1,27577,1,25,24,-0.734281,-1.095813,5
4,0,1,42658,1,47,45,-0.554148,-0.682077,5

In [18]:
df.to_csv("cleaned_visa_dataset.csv", index=False)

In [19]:
import joblib

joblib.dump(encoder, "encoder.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']